meta_product_name: "Suitbertus LearnWeb"
meta_title: "Suitbertus LearnWeb"
meta_description: "Hier findest du alte Klausuren, kannst dich mit Mitschülern austauschen und Lehrer bewerten."
meta_image: "home-banner.jpg" # should exist in `app/assets/images/`
twitter_account: "@LearnWeb" # required for Twitter Cards
